
# The log file location   
log:
filename: "urcpp.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Inventory
    - Bow
    - Order
    - Customer
    - Status
    - OrderDesign
    - Design
    - User
    
# this makes the navigation bar
mainMenu:
  - title: "Orders"
    link: "/orders"
  - title: "Inventory"
    link: "/inventory"
  - title: "Customers"
    link: "/customers"
  - title: "Designs"
    link: "/designs"
  - title: "New User"
    link: "/add/user"

